### PR TITLE
Categorize all the current commands

### PR DESCRIPTION
**Pull request by Crystalwarrior**
image
Closes https://github.com/AnidemDex/Blockflow/issues/123

### CODE REVIEW

**Comment by Crystalwarrior** [comment]
Maybe "editing" instead of "manipulation"?

**Comment by AnidemDex** [comment]
What about "engine"?

**Comment by Crystalwarrior** [comment]
ehhh, "Engine" might be a bit too broad

**Comment by AnidemDex** [comment]
What about "gameplay"? Somehow I don't think progressive verbs work as a category name

**Review by AnidemDex — CHANGES_REQUESTED** [review]
We probably will need a naming convention

**Review by AnidemDex — APPROVED** [review]
Welp, we'll see in the future how to name things

**Pull request merged**
